spring:
  application:
    name: book-api
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/assistant
    username: postgres
    password: root
  mail:
    host: mail.labellapartners.com
    port: 465
    username: assistant@labellapartners.com
    password: 3I8hNX6f6X
    protocol: smtp
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
            starttls.required: true
            ssl:
              enable: true
              trust: mail.labellapartners.com
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:3002,https://assistant.labellapartners.com

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG
